import 'package:image_picker/image_picker.dart';
import 'package:sixvalley_vendor_app/features/auction/domain/models/add_auction_product_model.dart';
import 'package:sixvalley_vendor_app/features/auction/domain/repository/add_auction_product_repository_interface.dart';
import 'package:sixvalley_vendor_app/features/auction/domain/services/add_auction_product_service_interface.dart';

class AddAuctionProductService implements AddAuctionProductServiceInterface {
  final AddAuctionProductRepositoryInterface auctionRepoInterface;
  AddAuctionProductService({required this.auctionRepoInterface});

  @override
  Future addAuctionProduct({
    required AddAuctionProductModel addAuctionProduct,
    required int categoryId,
    int? brandId,
    required String productType,
    required String itemCondition,
    required double entryFee,
    required double startingPrice,
    required double minimumIncrementAmount,
    required double maximumDecrementAmount,
    required String startTime,
    required String endTime,
    int? duration,
    required int status,
    required double shippingFee,
    String? returnPolicy,
    XFile? thumbnail,
    List<XFile>? images,
    String? videoType,
    String? youtubeVideo,
    XFile? customerVideo,
    List<int>? taxIds,
    String? metaTitle,
    String? metaDescription,
    String? metaIndex,
    String? metaNoFollow,
    String? metaNoImageIndex,
    String? metaNoArchive,
    String? metaNoSnippet,
    String? metaMaxSnippet,
    String? metaMaxSnippetValue,
    String? metaMaxVideoPreview,
    String? metaMaxVideoPreviewValue,
    String? metaMaxImagePreview,
    String? metaMaxImagePreviewValue,
    XFile? metaImageFile,
    String? metaImage,
    bool update = false,
    int? auctionId,
    List<String>? retainedImages,
    String? currentCurrencyCode,
    String? tags,
    bool isRelaunch = false,
  }) async {
    return await auctionRepoInterface.addAuctionProduct(
      addAuctionProduct: addAuctionProduct,
      categoryId: categoryId,
      brandId: brandId,
      productType: productType,
      itemCondition: itemCondition,
      entryFee: entryFee,
      startingPrice: startingPrice,
      minimumIncrementAmount: minimumIncrementAmount,
      maximumDecrementAmount: maximumDecrementAmount,
      startTime: startTime,
      endTime: endTime,
      duration: duration,
      status: status,
      shippingFee: shippingFee,
      returnPolicy: returnPolicy,
      thumbnail: thumbnail,
      images: images,
      videoType: videoType,
      youtubeVideo: youtubeVideo,
      customerVideo: customerVideo,
      taxIds: taxIds,
      metaTitle: metaTitle,
      metaDescription: metaDescription,
      metaIndex: metaIndex,
      metaNoFollow: metaNoFollow,
      metaNoImageIndex: metaNoImageIndex,
      metaNoArchive: metaNoArchive,
      metaNoSnippet: metaNoSnippet,
      metaMaxSnippet: metaMaxSnippet,
      metaMaxSnippetValue: metaMaxSnippetValue,
      metaMaxVideoPreview: metaMaxVideoPreview,
      metaMaxVideoPreviewValue: metaMaxVideoPreviewValue,
      metaMaxImagePreview: metaMaxImagePreview,
      metaMaxImagePreviewValue: metaMaxImagePreviewValue,
      metaImageFile: metaImageFile,
      metaImage: metaImage,
      update: update,
      auctionId: auctionId,
      retainedImages: retainedImages,
      currentCurrencyCode: currentCurrencyCode,
      tags: tags,
      isRelaunch: isRelaunch,
    );
  }
}
